# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsopnqfQzXO3US8DLGemsQ1-lLHHlmKH

# CAR MIELAGE PREDICTION

SOURCE - this data is taken from the YBI Foundation

ATTRIBUTE -
mpg : Continuous

cylinders : multi-valued discrete

displacement  : Continuous

horsepower : continuous

weight : countinous

acceleration : Continuous

model year : multi-valued discrete

origin : multi-valued
"""

import pandas as pd

import seaborn as sns

import numpy as np

import matplotlib.pyplot as plt

car=pd.read_csv("https://github.com/YBIFoundation/Dataset/raw/main/MPG.csv")

"""DATA PREPROCESSING"""

car.head()

car.info()

car.describe()

car.nunique()

"""# MISSING VALUE"""

car = car.dropna()

car.info()

"""# DATA VISUALIZATION"""

sns.pairplot(car, x_vars= ['displacement','horsepower','weight','acceleration','mpg'], y_vars=['mpg'])

sns.regplot(x='displacement',y='mpg',data=car);

"""# TARGETING VARIABLES"""

car.columns

y = car ['mpg']

y.shape

x = car [['displacement','horsepower','weight','acceleration']]

x.shape

x

"""# TRAIN TEST SPLIT"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=2529)

x_train.shape,x_test.shape,y_train.shape,y_test.shape

"""# LINEAR REGRESSION MODEL"""

from sklearn.linear_model import LinearRegression

ir = LinearRegression()

ir.fit(x_train, y_train)

ir.intercept_

ir.coef_

"""MIELAGE = 45.10, DISPLACEMENT 0.01, HOURSEPOWER 0.4, WEIGHT 0.4, ACCELERATION + EROOR 0.4

# PREDICT THE TEST DATA
"""

y_pred = ir.predict(x_test)

y_pred

"""# MODEL ACCURACY"""

from sklearn.metrics import mean_absolute_percentage_error

mean_absolute_percentage_error(y_test,y_pred)

mean_absolute_percentage_error(y_test,y_pred)

"""EXPLAINATION --

Regression analysis is a powerful tool for predicting car mileage based on various factors. By understanding the relationships between variables, you can make informed predictions and decisions.

Steps in Regression Analysis for Mileage Prediction:

Data Collection: Gather data related to car features (independent variables) and their corresponding mileage (dependent variable).

Data Preprocessing: Clean the data, handle missing values, and perform feature scaling if necessary.

Exploratory Data Analysis (EDA): Analyze the data to understand relationships, distributions, and correlations between variables.

Model Selection: Choose between simple or multiple linear regression based on the number of independent variables.

Model Training: Fit the regression model to the training data. This involves estimating the coefficients (slopes) that minimize the difference between the observed mileage and the predicted mileage.

Model Evaluation: Use metrics such as R-squared, Mean Absolute Error (MAE), or Root Mean Squared Error (RMSE) to assess how well the model predicts mileage.

Mileage=40−0.05(Engine Size)−0.02(Weight)+0.03(Horsepower)
This equation tells you how each feature impacts the mileage. For example, increasing the engine size by one unit might decrease the mileage by 0.05 units, assuming other variables remain constant.

Prediction: Once the model is trained and validated, it can be used to predict the mileage of new cars based on their features.

"""

